[2025-03-09 10:12:16,397: INFO: main: Welcome to our log]
[2025-03-10 10:06:37,991: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-10 10:06:37,992: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 10:06:37,993: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 10:06:37,993: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Applications/AI/Kidney/src/cnnClassifier/utils/common.py", line 33, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box/box.py", line 295, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/AI/Kidney/main.py", line 9, in <module>
    obj.main()
  File "/Applications/AI/Kidney/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/AI/Kidney/src/cnnClassifier/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lenguyen/.pyenv/versions/3.11.9/lib/python3.11/site-packages/ensure/main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/AI/Kidney/src/cnnClassifier/utils/common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2025-03-10 10:06:50,684: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-10 10:06:50,685: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 10:06:50,686: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 10:06:50,687: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/Applications/AI/Kidney/src/cnnClassifier/utils/common.py", line 33, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box/box.py", line 295, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/AI/Kidney/main.py", line 9, in <module>
    obj.main()
  File "/Applications/AI/Kidney/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/AI/Kidney/src/cnnClassifier/config/configuration.py", line 12, in __init__
    self.params = read_yaml(params_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lenguyen/.pyenv/versions/3.11.9/lib/python3.11/site-packages/ensure/main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/AI/Kidney/src/cnnClassifier/utils/common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2025-03-10 10:08:53,619: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-10 10:08:53,620: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 10:08:53,622: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 10:08:53,623: INFO: common: created directory at: artifacts]
[2025-03-10 10:08:53,623: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-10 10:08:53,623: INFO: data_ingestion: Downloading data from url="https://drive.google.com/file/d/16bY78PUqMqDF9DmrRRrma3rOAgYhvIA9/view?usp=sharing" into file artifacts/data_ingestion/data.zip]
[2025-03-10 10:09:47,549: INFO: data_ingestion: Downloaded data from url="https://drive.google.com/file/d/16bY78PUqMqDF9DmrRRrma3rOAgYhvIA9/view?usp=sharing" into file artifacts/data_ingestion/data.zip]
[2025-03-10 10:10:00,630: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-10 10:11:35,104: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-10 10:11:35,106: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 10:11:35,107: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 10:11:35,108: INFO: common: created directory at: artifacts]
[2025-03-10 10:11:35,108: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-10 10:11:35,108: INFO: data_ingestion: Downloading data from url="https://drive.google.com/file/d/16bY78PUqMqDF9DmrRRrma3rOAgYhvIA9/view?usp=sharing" into file artifacts/data_ingestion/data.zip]
[2025-03-10 10:12:26,939: INFO: data_ingestion: Downloaded data from url="https://drive.google.com/file/d/16bY78PUqMqDF9DmrRRrma3rOAgYhvIA9/view?usp=sharing" into file artifacts/data_ingestion/data.zip]
[2025-03-10 10:12:36,487: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-10 10:44:17,415: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 10:44:17,431: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 10:44:17,444: INFO: common: created directory at: artifacts]
[2025-03-10 10:44:17,445: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-10 10:44:22,864: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-10 10:44:23,032: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-03-10 10:44:23,038: WARNING: __init__: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-03-10 10:59:01,801: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-10 10:59:01,804: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 10:59:01,806: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 10:59:01,808: INFO: common: created directory at: artifacts]
[2025-03-10 10:59:01,808: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-10 10:59:01,808: INFO: data_ingestion: Downloading data from url="https://drive.google.com/file/d/16bY78PUqMqDF9DmrRRrma3rOAgYhvIA9/view?usp=sharing" into file artifacts/data_ingestion/data.zip]
[2025-03-10 10:59:48,078: INFO: data_ingestion: Downloaded data from url="https://drive.google.com/file/d/16bY78PUqMqDF9DmrRRrma3rOAgYhvIA9/view?usp=sharing" into file artifacts/data_ingestion/data.zip]
[2025-03-10 10:59:56,352: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-10 10:59:56,353: INFO: main: *******************]
[2025-03-10 10:59:56,353: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-10 10:59:56,355: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 10:59:56,358: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 10:59:56,360: INFO: common: created directory at: artifacts]
[2025-03-10 10:59:56,360: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-10 10:59:56,829: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-03-10 10:59:56,979: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-03-10 10:59:57,106: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-10 11:05:46,853: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 11:05:46,861: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 11:05:46,862: INFO: common: created directory at: artifacts]
[2025-03-10 11:05:46,865: INFO: common: created directory at: artifacts/training]
[2025-03-10 11:06:05,796: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-10 11:06:05,799: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 11:06:05,801: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 11:06:05,802: INFO: common: created directory at: artifacts]
[2025-03-10 11:06:05,802: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-10 11:06:05,802: INFO: data_ingestion: Downloading data from url="https://drive.google.com/file/d/16bY78PUqMqDF9DmrRRrma3rOAgYhvIA9/view?usp=sharing" into file artifacts/data_ingestion/data.zip]
[2025-03-10 11:06:54,168: INFO: data_ingestion: Downloaded data from url="https://drive.google.com/file/d/16bY78PUqMqDF9DmrRRrma3rOAgYhvIA9/view?usp=sharing" into file artifacts/data_ingestion/data.zip]
[2025-03-10 11:07:02,651: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-10 11:07:02,652: INFO: main: *******************]
[2025-03-10 11:07:02,652: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-10 11:07:02,654: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 11:07:02,657: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 11:07:02,659: INFO: common: created directory at: artifacts]
[2025-03-10 11:07:02,659: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-10 11:07:03,100: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-03-10 11:07:03,237: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-03-10 11:07:03,361: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-10 11:07:23,097: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 11:07:23,101: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 11:07:23,103: INFO: common: created directory at: artifacts]
[2025-03-10 11:07:23,105: INFO: common: created directory at: artifacts/training]
[2025-03-10 11:08:06,024: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-10 11:08:06,028: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-10 11:08:06,031: INFO: common: created directory at: artifacts]
[2025-03-10 11:08:06,034: INFO: common: created directory at: artifacts/training]
